name: Deploy

on:
  workflow_dispatch:
     
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      # 1. Baixa o código do seu repositório
      - uses: actions/checkout@v4
      
      # 2. Instala a versão correta do pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # 3. Instala as dependências do projeto
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4. Executa o deploy com as informações necessárias
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }} # Adicionado para especificar a conta de destino
          # O comando padrão da action é 'wrangler deploy', então essa linha é opcional, mas boa para clareza
          command: deploy
